"""
TaxGuru — Expanded Tax Law Knowledge Base v2
45+ entries covering ALL taxpayer types
FY 2025-26 (AY 2026-27)
"""

TAX_KNOWLEDGE_BASE = [
    {"id":"new_regime_slabs","section":"115BAC","category":"tax_slabs","applies_to":["all"],"title":"New Tax Regime Slabs FY 2025-26","content":"Under Section 115BAC (default):\n0-4L: Nil, 4-8L: 5%, 8-12L: 10%, 12-16L: 15%, 16-20L: 20%, 20-24L: 25%, >24L: 30%.\nStandard deduction: 75K (salaried). 87A rebate: 60K for income up to 12L. Effectively 12.75L tax-free for salaried.\nMost deductions NOT available except: Employer NPS (80CCD(2)), Agniveer (80CCH), professional tax.","last_updated":"2025-07-01","source":"Finance Act 2025"},
    {"id":"old_regime_slabs","section":"Various","category":"tax_slabs","applies_to":["all"],"title":"Old Tax Regime Slabs FY 2025-26","content":"<60: 0-2.5L Nil, 2.5-5L 5%, 5-10L 20%, >10L 30%. Senior(60-80): 3L exempt. Super(80+): 5L exempt.\nStd deduction 50K. 87A rebate 12.5K (income up to 5L). All Chapter VI-A deductions available.\nFor non-business: switch every year. Business: restricted.","last_updated":"2025-07-01","source":"IT Act 1961"},
    {"id":"regime_comparison","section":"115BAC","category":"planning","applies_to":["all"],"title":"Old vs New Regime Decision Framework","content":"NEW better if: deductions < ~3.75L, no HRA/home loan, income ≤ 12.75L.\nOLD better if: HRA + 80C(1.5L) + 80CCD1B(50K) + 80D(25-100K) + 24b(2L) > 3.75L.\nBreak-even at 15L: old better if deductions > 2.5L. At 20L: > 3.75L.\nBusiness income: once opt out of new, can return only ONCE.","last_updated":"2025-07-01","source":"Analysis"},
    {"id":"surcharge_cess","section":"Various","category":"tax_computation","applies_to":["all"],"title":"Surcharge and Cess","content":"Old surcharge: >50L 10%, >1Cr 15%, >2Cr 25%, >5Cr 37%. New: max 25%.\nCapital gains (111A/112A): max surcharge 15%.\nMarginal relief available. CESS: 4% on (tax+surcharge), always.","last_updated":"2025-07-01","source":"Finance Act 2025"},
    {"id":"section_80c","section":"80C","category":"deductions","applies_to":["salaried","business","professional"],"title":"Section 80C — Investments (Max 1.5L)","content":"OLD REGIME ONLY, max 1.5L combined: EPF, PPF(max 1.5L/yr, 7.1%, 15yr lock-in, EEE), ELSS(3yr lock-in, equity), NSC, Tax saver FD(5yr), LIC(max 10% sum assured), Sukanya Samriddhi, Tuition(2 children), Home loan principal, SCSS, NABARD bonds, ULIP, Stamp duty.","last_updated":"2025-07-01","source":"Section 80C"},
    {"id":"section_80d","section":"80D","category":"deductions","applies_to":["all"],"title":"Section 80D — Health Insurance","content":"OLD REGIME. Self/family: 25K (50K if senior). Parents: additional 25K (50K if senior). Max 1L.\nPreventive checkup: 5K within limits. Cash NOT eligible.","last_updated":"2025-07-01","source":"Section 80D"},
    {"id":"section_80ccd","section":"80CCD","category":"deductions","applies_to":["salaried","self_employed"],"title":"Section 80CCD — NPS","content":"80CCD(1): Employee NPS up to 10% salary (20% self-employed), within 80C. OLD REGIME.\n80CCD(1B): Additional 50K OVER 80C limit. OLD REGIME.\n80CCD(2): Employer NPS up to 14% salary. BOTH REGIMES — most valuable new regime deduction.","last_updated":"2025-07-01","source":"Section 80CCD"},
    {"id":"section_80e","section":"80E","category":"deductions","applies_to":["all"],"title":"Section 80E — Education Loan Interest (No Limit)","content":"OLD REGIME. Interest on education loan, NO UPPER LIMIT. 8 years from start of repayment.\nLoan from financial institution. For higher education (post Class 12) of self/spouse/children/ward.\nOnly interest deductible, not principal. Valuable for MBA/professional degree loans.","last_updated":"2025-07-01","source":"Section 80E"},
    {"id":"section_80g","section":"80G","category":"deductions","applies_to":["all"],"title":"Section 80G — Donations","content":"OLD REGIME. 100% no limit: PM National Relief Fund, National Defence Fund, PM CARES.\n100% with 10% GTI limit: Approved institutions. 50% with limit: Other eligible.\nCash > 2K: NOT eligible.","last_updated":"2025-07-01","source":"Section 80G"},
    {"id":"section_80tta_80ttb","section":"80TTA/80TTB","category":"deductions","applies_to":["all"],"title":"80TTA & 80TTB — Interest Deductions","content":"80TTA: Savings interest up to 10K (<60, OLD REGIME). NOT FD interest.\n80TTB: ALL deposit interest up to 50K for seniors (60+, OLD REGIME). Replaces 80TTA.\nMutually exclusive.","last_updated":"2025-07-01","source":"80TTA, 80TTB"},
    {"id":"hra_exemption","section":"10(13A)","category":"exemptions","applies_to":["salaried"],"title":"HRA Exemption","content":"OLD REGIME. Exempt = MIN of: (1) Actual HRA, (2) 50% basic (metro) or 40% (non-metro), (3) Rent-10% basic.\nMetro: Delhi/Mumbai/Chennai/Kolkata only. Cannot claim HRA + 24b on same property.\nRent receipts needed. Landlord PAN if rent > 1L/yr. No HRA component: claim 80GG(max 5K/month).","last_updated":"2025-07-01","source":"Section 10(13A), Rule 2A"},
    {"id":"section_10_exemptions","section":"10","category":"exemptions","applies_to":["salaried"],"title":"Section 10 Salary Exemptions (Old Regime)","content":"10(5): LTA — actual travel, 2 journeys in 4yr block. 10(14): Children education 100/month, hostel 300/month (2 children).\n10(10): Gratuity exempt up to 20L (non-govt). 10(10A): Commuted pension 1/3 or 1/2 exempt.\n10(10AA): Leave encashment on retirement up to 25L. 10(10D): LIC maturity exempt if premium < 10% SA.","last_updated":"2025-07-01","source":"Section 10"},
    {"id":"house_property_self","section":"23,24","category":"house_property","applies_to":["all"],"title":"Self-Occupied House Property","content":"GAV = NIL for self-occupied. Only benefit: home loan interest under 24(b), max 2L (OLD REGIME).\nPre-construction interest: 5 equal installments after completion. Must complete within 5 years.\nNEW REGIME: No 24(b) for self-occupied. Max 2 self-occupied properties (from AY 2020-21).","last_updated":"2025-07-01","source":"Sections 23, 24(b)"},
    {"id":"house_property_letout","section":"22-27","category":"house_property","applies_to":["all"],"title":"Let-Out & Deemed Let-Out Property","content":"GAV = higher of actual rent or expected rent. Vacancy allowance available.\nNAV = GAV - municipal taxes. Std deduction: 30% of NAV (flat). Interest: NO LIMIT (both regimes).\nHP loss: set off up to 2L against other income, balance carry forward 8 years.\nDeemed let-out: own >2 houses, excess at fair rent. Co-owners: each taxed on share.","last_updated":"2025-07-01","source":"Sections 22-27"},
    {"id":"capital_gains_exemption_property","section":"54,54F,54EC","category":"house_property","applies_to":["all"],"title":"Capital Gains Exemption on Property Sale","content":"Sec 54: LTCG on house sale exempt if new house bought within 2yr/built 3yr. Two houses if LTCG ≤ 2Cr (once).\nSec 54F: LTCG on ANY non-house asset exempt if net consideration invested in house. Must not own >1 house.\nSec 54EC: LTCG up to 50L in NHAI/REC bonds within 6 months. 5yr lock-in.\nPost Jul 2024: LTCG on property = 12.5% without indexation. CGAS deposit if not invested by ITR due date.","last_updated":"2025-07-01","source":"Sections 54, 54F, 54EC"},
    {"id":"business_income","section":"28-37","category":"business","applies_to":["business","professional"],"title":"Business Income — Computation & Expenses","content":"Profit = Revenue - expenses. Allowable: rent/rates/taxes(30-31), depreciation(32: building 10%, computer 40%, vehicle 15-30%), repairs, salary, interest on business borrowing(36(1)(iii)), bad debts(36(1)(vii)), employer RPF/pension, prelim expenses(35D: 1/5 x 5yr).\nDISALLOWED(40/40A): personal, income tax, cash > 10K/person/day(40A(3)), TDS not deducted(40(a)(ia)).","last_updated":"2025-07-01","source":"Sections 28-44"},
    {"id":"presumptive_taxation","section":"44AD,44ADA,44AE","category":"business","applies_to":["business","professional"],"title":"Presumptive Taxation","content":"44AD: Turnover ≤ 2Cr (3Cr if 95% digital). Declare ≥ 6% (8% cash). No books needed at threshold. Opt-out: can't return 5yr.\n44ADA: Specified professions (legal/medical/engg/arch/CA/tech consultancy/interior/film). Receipts ≤ 50L (75L digital). Declare ≥ 50%.\n44AE: Goods carriers, ≤ 10 vehicles, 7.5K/month/vehicle.","last_updated":"2025-07-01","source":"Sections 44AD, 44ADA, 44AE"},
    {"id":"depreciation","section":"32","category":"business","applies_to":["business","professional"],"title":"Depreciation on Business Assets","content":"WDV method. Building 10%, furniture 10%, plant 15%, computer 40%, vehicle 15-30%, intangibles 25%.\nAdditional 20% on new manufacturing P&M. Half-year rule if used <180 days.\nUnabsorbed depreciation: carry forward INDEFINITELY.","last_updated":"2025-07-01","source":"Section 32, Rule 5"},
    {"id":"tax_audit","section":"44AB","category":"compliance","applies_to":["business","professional","trader"],"title":"Tax Audit Requirements","content":"Mandatory if: Business turnover > 1Cr (10Cr if 95% digital). Profession receipts > 50L.\nPresumptive: if declaring < threshold %. Due date: 30 Sep. Penalty: 0.5% of turnover or 1.5L, lower.\nF&O traders: turnover = sum of absolute P&L. Must audit if exceeding thresholds.","last_updated":"2025-07-01","source":"Section 44AB"},
    {"id":"capital_gains_equity","section":"111A,112A","category":"capital_gains","applies_to":["investor","trader"],"title":"Capital Gains on Equity (Post Jul 2024)","content":"Listed equity/equity MFs: STCG(<12m) 20% (Sec 111A). LTCG(≥12m) 12.5% (Sec 112A), first 1.25L exempt.\nUnlisted: STCG at slab, LTCG 12.5% (24m holding). Debt MFs (post Apr 2023): always slab rates (50AA).\nGold/ETF: LTCG after 24m at 12.5%. SGB to maturity: fully exempt.\nINDEXATION REMOVED for all assets from 23 Jul 2024.","last_updated":"2025-07-23","source":"Finance (No.2) Act 2024"},
    {"id":"capital_gains_property","section":"45,50C","category":"capital_gains","applies_to":["all"],"title":"Capital Gains on Real Estate","content":"Holding: ≥ 24m LTCG, <24m STCG. LTCG 12.5% (no indexation post Jul 2024). STCG slab rates.\nSec 50C: if sale < stamp duty value, stamp duty deemed as consideration (10% tolerance).\nTDS: Buyer 1% if > 50L (194-IA). Joint property: each owner on share. Inherited: holding includes previous owner.","last_updated":"2025-07-01","source":"Sections 45, 50C"},
    {"id":"capital_gains_bonds_debt","section":"112,50AA","category":"capital_gains","applies_to":["investor"],"title":"Capital Gains on Bonds, Debt, Gold","content":"Debt MFs (post Apr 2023): ALWAYS slab rates via 50AA. Listed bonds: STCG slab, LTCG(≥12m) 12.5%.\nUnlisted bonds: STCG slab, LTCG(≥24m) 12.5%. Gold ETFs: LTCG(≥24m) 12.5%.\nSGB held to maturity: FULLY EXEMPT. MLDs: always slab (50AA). REIT/InvIT: STCG 20%, LTCG 12.5% above 1.25L.","last_updated":"2025-07-01","source":"Sections 112, 50AA"},
    {"id":"fno_trading","section":"43(5)","category":"trading","applies_to":["trader"],"title":"F&O Trading — Non-Speculative Business","content":"F&O = NON-SPECULATIVE business income (Sec 43(5)). Tax at slab rates. File ITR-3 (or ITR-4 with 44AD).\nTurnover = sum of absolute P&L. Audit if > 10Cr(95% digital) or 1Cr. 44AD if ≤ 2Cr, declare ≥ 6%.\nLoss: set off against ALL except salary. Carry forward 8yr (only against non-speculative business).\nExpenses: brokerage, internet, advisory, electricity, rent, depreciation. MUST report even losses.\n93% of F&O traders lost money in FY23-24 (SEBI). Still must file.","last_updated":"2025-07-01","source":"Section 43(5), 44AB, 44AD"},
    {"id":"intraday_speculative","section":"43(5)","category":"trading","applies_to":["trader"],"title":"Intraday Equity — Speculative Income","content":"Intraday (no delivery) = SPECULATIVE business income. Tax at slab rates. ITR-3.\nSpeculative loss: ONLY against speculative profit. Carry forward 4 years.\nBTST: Debatable — generally delivery-based (STCG) if STT paid.\nCommodity derivatives: non-speculative (like F&O). Currency derivatives: non-speculative.","last_updated":"2025-07-01","source":"Section 43(5)"},
    {"id":"investor_vs_trader","section":"Various","category":"trading","applies_to":["investor","trader"],"title":"Investor vs Trader Classification","content":"No fixed rule. Depends on frequency, volume, intention, holding period, primary income source.\nCBDT Circular 6/2016: Can maintain two portfolios — investment(capital gains) + trading(business).\nCIT vs Gopal Purohit (Bombay HC): Same shares can be investment + trading.\nConsequence: Business = slab + expenses + advance tax + audit. Capital gains = special lower rates.","last_updated":"2025-07-01","source":"CBDT Circular 6/2016"},
    {"id":"esop_taxation","section":"17(2)(vi)","category":"esop","applies_to":["salaried","investor"],"title":"ESOP & Sweat Equity Taxation","content":"Exercise: Perquisite = FMV - exercise price. Taxed as salary, TDS by employer (Sec 192).\nSale: CG = sale price - FMV at exercise. Listed: STCG(<12m) 20%, LTCG 12.5%. Unlisted: STCG(<24m) slab, LTCG 12.5%.\nStartup deferral(80-IAC): 48 months or sale or leaving, whichever first. Only DPIIT-certified.\nForeign ESOPs: Same + FEMA compliance + Schedule FA + LRS + Form 67 for FTC.","last_updated":"2025-07-01","source":"Section 17(2)(vi), FEMA OI Rules"},
    {"id":"foreign_assets","section":"Schedule FA","category":"foreign_assets","applies_to":["investor","salaried"],"title":"Foreign Assets — Schedule FA Disclosure","content":"MANDATORY for residents: foreign bank accounts(even zero balance), securities(including ESOPs), property, signing authority, trusts.\nPenalty: 10L under Black Money Act 2015. Prosecution possible.\nFEMA: OPI if <10% holding. LRS: $250K/FY. TCS: 20% above 10L (education 5%, nil if specified loan).","last_updated":"2025-07-01","source":"Schedule FA, Black Money Act"},
    {"id":"nri_taxation","section":"5,6,90","category":"nri","applies_to":["nri"],"title":"NRI Taxation","content":"Only Indian-sourced income taxable. Resident if ≥182 days or ≥60+365 in prior 4yr.\nDeemed resident: Indian citizen, India income >15L, not tax resident elsewhere.\nRNOR: Indian income taxable, foreign not (2-3 years after return). DTAA with 90+ countries.\nForm 67 for FTC. Higher TDS rates (30%). NRE interest exempt, NRO taxable.","last_updated":"2025-07-01","source":"Sections 5, 6, 90"},
    {"id":"dtaa_ftc","section":"90,91","category":"nri","applies_to":["nri","investor"],"title":"DTAA & Foreign Tax Credit","content":"Relief: lower of Indian or foreign tax on doubly-taxed income. Per-country, per-source basis.\nForm 67: MUST file before ITR due date (SC relaxed for genuine cases). FTC cannot exceed Indian tax.\nSec 91: Unilateral relief if no DTAA. India DTAAs with US, UK, Singapore, UAE, etc.","last_updated":"2025-07-01","source":"Sections 90, 91, Rule 128"},
    {"id":"setoff_carry_forward","section":"70-80","category":"set_off","applies_to":["all"],"title":"Set-Off & Carry Forward of Losses","content":"Intra-head(70): Loss from one source vs profit in same head. Speculative only vs speculative. LTCL only vs LTCG.\nInter-head(71): Business loss vs any except salary. HP loss: up to 2L vs other income, balance 8yr.\nSTCL: vs any CG, 8yr. LTCL: only vs LTCG, 8yr. Unabsorbed depreciation: INDEFINITE.\nCRITICAL: file ITR by due date to carry forward (except HP loss and depreciation).","last_updated":"2025-07-01","source":"Sections 70-80"},
    {"id":"penalties","section":"234A/B/C,271","category":"penalties","applies_to":["all"],"title":"Penalties, Interest & Prosecution","content":"Late filing(234F): 5K (1K if income ≤5L). Late interest(234A): 1%/month on unpaid tax.\nAdvance tax shortfall(234B): 1%/month if <90%. Installment deferment(234C): 1%/month.\nUnder-reporting(270A): 50% of tax on under-reported. Misreporting: 200%.\nWillful non-filing(276CC): prosecution if evaded >25K. TDS failure(271C): penalty = TDS amount.\nBelated/Revised return: until 31 Dec of AY.","last_updated":"2025-07-01","source":"Sections 234, 270A, 271, 276CC"},
    {"id":"advance_tax","section":"208-211","category":"compliance","applies_to":["business","professional","trader","investor"],"title":"Advance Tax","content":"Payable if estimated tax > 10K. Due: 15 Jun 15%, 15 Sep 45%, 15 Dec 75%, 15 Mar 100%.\nExempt: seniors(60+) with no business income. CG after due date: pay in remaining installments.\nPresumptive(44AD/ADA): entire by 15 Mar. F&O traders: mandatory.","last_updated":"2025-07-01","source":"Sections 208-211"},
    {"id":"tds_provisions","section":"192-206","category":"tds","applies_to":["all"],"title":"Key TDS Provisions","content":"192: Salary. 194A: Interest 10% if >40K(50K seniors, 1L from FY25-26). 194B: Lottery 30% >10K.\n194H: Commission 5% >15K. 194-I: Rent 2%/10% >2.4L. 194-IA: Property 1% >50L. 194-IB: Rent by individual 2% >50K/m(6L/yr FY25-26).\n194J: Prof fees 10% >30K. 194N: Cash 2% >1Cr(filers). 206C(1G): LRS 20% >10L. Form 15G/15H to avoid.","last_updated":"2025-07-01","source":"Sections 192-206"},
    {"id":"crypto","section":"115BBH","category":"crypto","applies_to":["investor","trader"],"title":"Crypto/VDA Taxation","content":"Flat 30% on profits. NO deductions except cost. NO set-off. NO carry forward.\nTDS(194S): 1% if >50K/yr. Gifts of crypto: taxable at 30%.\nMining/staking: likely slab rates (not explicitly clarified). Strictest regime globally.","last_updated":"2025-07-01","source":"Section 115BBH"},
    {"id":"senior_citizen","section":"Various","category":"senior_citizen","applies_to":["senior_citizen"],"title":"Senior Citizen Benefits","content":"Old: Senior(60-80) 3L exempt, Super(80+) 5L. New: no special exemption.\n80D: 50K limit. 80TTB: 50K interest. TDS threshold 1L(FY25-26). Form 15H.\nNo advance tax if no business income. 194P: Banks can file for seniors ≥75(single bank).\nPension: taxable as salary. Commuted: govt exempt, others 1/3 or 1/2. Reverse mortgage: not taxable.","last_updated":"2025-07-01","source":"Various"},
    {"id":"home_loan","section":"24(b),80C,80EE","category":"deductions","applies_to":["all"],"title":"Home Loan Tax Benefits","content":"Interest 24(b): Self-occupied 2L max (OLD). Let-out: no limit (BOTH). Principal 80C: within 1.5L (OLD).\nPre-construction interest: 5 installments. Must complete in 5yr. Stamp duty under 80C.\n80EE: 50K (first-time, FY16-17 loan, stamp ≤50L, loan ≤35L). 80EEA: 1.5L (affordable, stamp ≤45L, loan Apr19-Mar22).\nJoint: each claims proportionate. NEW REGIME: only let-out interest (no limit).","last_updated":"2025-07-01","source":"Sections 24(b), 80C, 80EE"},
    {"id":"professional_tax","section":"16(iii)","category":"deductions","applies_to":["salaried","professional"],"title":"Professional Tax","content":"State-level, max 2.5K/yr. Deductible in BOTH regimes under Sec 16(iii).\nLevied in: MH, KA, WB, AP, TG, TN, GJ, MP, KL, etc. NOT in: Delhi, RJ, UP, UK, HR, PB, HP.","last_updated":"2025-07-01","source":"Article 276, Sec 16(iii)"},
    {"id":"gift_taxation","section":"56(2)(x)","category":"other_income","applies_to":["all"],"title":"Gift Taxation","content":"Tax-free: from relatives, on marriage, by will/inheritance, from local authority.\nTaxable if aggregate >50K from non-relatives: money(full), property(if stamp >50K, >10% gap), movable(if FMV >50K).\nInherited property: no tax on receipt. CG on sale: cost = previous owner's, holding includes theirs.","last_updated":"2025-07-01","source":"Section 56(2)(x)"},
    {"id":"clubbing","section":"60-65","category":"anti_avoidance","applies_to":["all"],"title":"Clubbing of Income","content":"Sec 60: income transfer without asset transfer = clubbed. 64(1)(ii): asset to spouse without consideration = clubbed.\n64(1)(iv): spouse's investment from gifted funds = clubbed (except salary). 64(1A): minor child income clubbed with higher-income parent, 1.5K/child exempt.\nException: minor's skill/talent/disability income not clubbed.","last_updated":"2025-07-01","source":"Sections 60-65"},
    {"id":"angel_tax","section":"56(2)(viib)","category":"startup","applies_to":["business"],"title":"Angel Tax — ABOLISHED from Apr 2025","content":"Was: shares at premium > FMV taxable for closely-held companies.\nBudget 2024: ABOLISHED from 1 Apr 2025 for ALL investors (resident + non-resident).\nNow: No angel tax. Companies can raise at any premium. Major startup ecosystem relief.","last_updated":"2025-04-01","source":"Finance (No.2) Act 2024"},
    {"id":"case_law_hra","section":"10(13A)","category":"case_law","applies_to":["salaried"],"title":"Case Law: HRA — Rent to Parents/Spouse","content":"Rent to parents: ALLOWED if genuinely paid, include in parents' income. ITAT supports with agreement + receipts.\nRent to spouse: Generally NOT allowed if joint property or sham. Funds must not circle back.\nHRA + home loan: Cannot on SAME property. Different city: both claimable.\nMetro: Only Delhi/Mumbai/Chennai/Kolkata get 50%.","last_updated":"2025-07-01","source":"Various ITAT rulings"},
    {"id":"case_law_cg_classification","section":"45","category":"case_law","applies_to":["investor","trader"],"title":"Case Law: Capital Gains vs Business — Stock Trading","content":"CBDT Circular 6/2016: Two portfolios allowed — investment + trading, if consistent.\nCIT vs Gopal Purohit (Bombay HC): Taxpayer intention matters, same shares can be both.\nITAT factors: frequency, holding period, volume vs total income, leverage use.\nDelivery >1yr: generally capital gains. High-frequency <1yr: likely business.","last_updated":"2025-07-01","source":"CBDT Circular 6/2016, Bombay HC"},
    {"id":"case_law_esop_nri","section":"17(2)(vi),90","category":"case_law","applies_to":["salaried","nri"],"title":"Case Law: ESOP for NRIs — Cross-Border","content":"Unnikrishnan vs ITO (Mumbai ITAT): ESOPs granted as resident but exercised as NRI — taxable in India.\nPerquisite accrual ≠ receipt. Taxable where services rendered during vesting.\nApportionment: perquisite split by days of India employment during vesting.\nFTC via DTAA if tax abroad. Form 67 required. Maintain all documentation.","last_updated":"2025-07-01","source":"Unnikrishnan vs ITO (Mumbai ITAT)"},
    {"id":"case_law_wfh","section":"Various","category":"case_law","applies_to":["salaried"],"title":"WFH Expenses — No Deduction for Salaried","content":"No specific WFH deduction for salaried employees in India (unlike Australia/Germany).\nSalaried: internet, electricity, furniture NOT deductible beyond standard deduction.\nBusiness/Professional: CAN claim WFH expenses. F&O traders: CAN claim proportionally.\nIndustry advocacy for WFH deduction — not yet implemented.","last_updated":"2025-07-01","source":"Current provisions"},
    {"id":"rental_income_tds","section":"194-I,194-IB","category":"tds","applies_to":["all"],"title":"TDS on Rental Income","content":"Non-individual tenant (194-I): 2%(P&M) or 10%(land/building) if rent >2.4L/yr.\nIndividual tenant (194-IB): 2% if >50K/month (6L/yr from FY25-26).\nLandlord: report income, 30% std deduction of NAV, municipal taxes deductible.","last_updated":"2025-07-01","source":"Sections 194-I, 194-IB"},
    {"id":"new_it_act_2025","section":"IT Act 2025","category":"legislation","applies_to":["all"],"title":"New Income Tax Act 2025","content":"Replaces IT Act 1961. Effective 1 Apr 2026. Simplifies language, reorganizes sections.\nNo rate changes. Same deductions/exemptions with new section numbers. Two regimes continue.\nMinimal immediate impact on liability — mainly organizational.","last_updated":"2026-02-01","source":"Budget 2025"},
    {"id":"budget_2026","section":"Finance Act 2026","category":"legislation","applies_to":["all"],"title":"Budget 2026","content":"NO changes to slabs for FY 2026-27. New IT Act 2025 takes effect Apr 2026.\nStd deduction 75K, 87A rebate 60K (income up to 12L) — unchanged.\nCG rates unchanged: STCG equity 20%, LTCG equity 12.5%. Focus: infra, defence, MSMEs.","last_updated":"2026-02-01","source":"Budget 2026"},

    {"id":"it_rules_2026","section":"IT Rules 2026","category":"legislation","applies_to":["all"],"title":"Income Tax Rules 2026 — Notified March 20, 2026","content":"CBDT Notification No.22/2026 (March 20, 2026): Income-tax Rules 2026 effective April 1, 2026.\nKey changes:\n- HRA metro cities EXPANDED to 8: Mumbai, Delhi, Kolkata, Chennai, Hyderabad, Pune, Ahmedabad, Bengaluru (50% of basic). All others 40%.\n- Form 124 replaces Form 12BB for HRA claims. Must disclose landlord relationship if rent > 1L/yr.\n- Sections reduced from 819 to 536, chapters from 47 to 23.\n- Businesses up to 10Cr turnover (conditions apply) exempt from detailed books and audit.\n- Crypto/VDA: CARF (Crypto-Asset Reporting Framework) aligned with OECD CRS.\n- Transfer pricing: IT services safe harbour margin 15.5%.\n- Insurance premium reporting threshold: 5L (with PAN), 2.5L (without).","last_updated":"2026-03-20","source":"CBDT Notification 22/2026, Gazette of India"},
    {"id":"hra_8_cities","section":"10(13A)","category":"exemptions","applies_to":["salaried"],"title":"HRA — 8 Metro Cities from April 2026","content":"FROM APRIL 1, 2026 (IT Rules 2026):\n50% HRA cities EXPANDED from 4 to 8:\n1. Delhi 2. Mumbai 3. Kolkata 4. Chennai 5. Hyderabad 6. Pune 7. Ahmedabad 8. Bengaluru\nAll other cities: 40% of basic salary.\nNEW: Form 124 mandatory for HRA claims. Must disclose landlord name, PAN, and RELATIONSHIP if rent > 1L/yr (especially rent to parents/siblings/spouse).\nNote: For FY 2025-26 (current year), only 4 cities (Del/Mum/Kol/Che) qualify. 8-city rule applies from FY 2026-27.","last_updated":"2026-03-20","source":"IT Rules 2026, CBDT Notification 22/2026"},
    {"id":"cbdt_scrutiny_2025","section":"143(2)","category":"compliance","applies_to":["all"],"title":"CBDT Scrutiny Guidelines FY 2025-26","content":"Compulsory scrutiny triggers for FY 2025-26:\n- Survey conducted on/after April 1, 2023\n- Search/requisition (132/132A) between Apr 2023-Mar 2025\n- Repeated contentious claims disallowed in 3+ years and upheld by ITAT/HC\n- Intelligence alerts: undisclosed foreign income, benami transactions, bogus donations, GST mismatches\n- ITR-7 exemption claims\nNotice under 143(2) must be issued by June 30, 2025 for AY 2025-26.\nACTION: Cross-verify with Form 26AS, AIS, TIS before filing. Keep documentation for all deductions.","last_updated":"2025-06-01","source":"CBDT Scrutiny Guidelines FY 2025-26"},
    {"id":"carf_crypto_2026","section":"285BA","category":"crypto","applies_to":["investor","trader"],"title":"CARF — Crypto Asset Reporting Framework (2026)","content":"CBDT Amendment Rules 2026 (March 5, 2026): India adopts OECD CARF.\nReporting financial institutions must report crypto/VDA transactions.\nNew due diligence procedures for accounts treated as financial accounts due to CRS amendments.\nOperative date: January 1, 2026 for new accounts. Pre-existing: as of Dec 31, 2025.\nSelf-certification required from account holders. Transitional relief for pre-existing accounts.\nIMPACT: All crypto exchanges and custodians in India must now report to tax authorities, making it much harder to evade crypto taxes.","last_updated":"2026-03-05","source":"CBDT Amendment Rules 2026, GSR 158(E)"},


    {"id":"residency_rules","section":"6","category":"nri","applies_to":["nri","all"],"title":"Tax Residency Determination Rules","content":"HOW TO DETERMINE YOUR RESIDENCY STATUS (Section 6):\nYou are RESIDENT if: (a) You were in India ≥182 days in the financial year, OR (b) You were in India ≥60 days in the FY AND ≥365 days in the 4 preceding FYs.\nEXCEPTIONS to 60-day rule: Indian citizens going abroad for employment or as ship crew → only 182-day rule applies. Indian citizens/PIOs visiting India with Indian income ≤15L → only 182-day rule. Indian citizens/PIOs with Indian income >15L → 120 days (not 60).\nDEEMED RESIDENT (Section 6(1A)): Indian citizen earning >15L from Indian sources AND not tax resident of any other country → deemed resident (taxed as RNOR).\nRNOR: Resident who was NRI in 9 of 10 preceding years, OR stayed <730 days in preceding 7 years.\nTAXATION: Resident = global income taxed. NRI = only Indian income. RNOR = only Indian income (like NRI).\nFROM APRIL 2026: Tax Year concept replaces Previous Year/Assessment Year terminology.","last_updated":"2026-03-20","source":"Section 6, IT Act; IT Bill 2025"},
    {"id":"agricultural_income","section":"10(1)","category":"exemptions","applies_to":["all"],"title":"Agricultural Income — Fully Exempt","content":"Agricultural income is FULLY EXEMPT from income tax under Section 10(1).\nIncludes: rent from agricultural land, income from cultivation, income from farm buildings.\nBUT: If total income (non-agricultural) > basic exemption AND agricultural income > ₹5,000 → partial integration method applies for rate purposes.\nPartial integration: Add agricultural + non-agricultural income → compute tax → subtract tax on agricultural income alone at slab rates → difference is your tax.\nFarmhouse income: Exempt only if farmhouse is on or in immediate vicinity of agricultural land.\nNote: State governments can tax agricultural income separately.","last_updated":"2025-07-01","source":"Section 10(1)"},
    {"id":"section_87a_marginal","section":"87A","category":"tax_computation","applies_to":["all"],"title":"Section 87A Rebate and Marginal Relief","content":"Section 87A provides a rebate to reduce tax to NIL for low-income taxpayers.\nNEW REGIME: Rebate up to ₹60,000 if taxable income ≤ ₹12,00,000. Effectively: income up to ₹12L = zero tax. With ₹75K std deduction: salaried up to ₹12.75L = zero tax.\nOLD REGIME: Rebate up to ₹12,500 if taxable income ≤ ₹5,00,000.\nMARGINAL RELIEF: If income is slightly above ₹12L (new regime), tax payable cannot exceed the amount by which income exceeds ₹12L. Example: Income ₹12.1L → tax cannot exceed ₹10,000 (the excess over ₹12L).\nIMPORTANT: 87A rebate does NOT apply to special rate income (LTCG, STCG under 111A). Only applies to normal slab income.\nNRI residents: 87A available only for RESIDENT individuals.","last_updated":"2025-07-01","source":"Section 87A, Finance Act 2025"},
    {"id":"itr_forms","section":"139","category":"compliance","applies_to":["all"],"title":"ITR Forms — Which One to File","content":"ITR-1 (Sahaj): Salary + 1 house property + other sources (interest, etc.). Income up to ₹50L. Resident individuals only. NOT for capital gains, business income, foreign assets, or >1 house property.\nITR-2: Individuals/HUFs with capital gains, foreign assets, >1 house property, income >₹50L. No business income.\nITR-3: Individuals/HUFs with business or professional income (including F&O traders).\nITR-4 (Sugam): Presumptive income under 44AD/44ADA/44AE. Turnover up to ₹2Cr (business) or ₹50L (profession).\nITR-5: Firms, LLPs, AOPs, BOIs.\nITR-6: Companies (other than those claiming exemption under Sec 11).\nITR-7: Trusts, political parties, institutions under Sec 139(4A/4B/4C/4D).\nDUE DATES: 31 July (non-audit), 31 October (audit), 30 November (transfer pricing).\nBELATED: Until 31 December of AY. REVISED: Until 31 December of AY.","last_updated":"2025-07-01","source":"Section 139, CBDT"},
    {"id":"cbdt_circular_15_2025","section":"119","category":"legislation","applies_to":["business","professional"],"title":"CBDT Circular 15/2025 — ITR Deadline Extension","content":"CBDT Circular 15/2025 (October 2025): Extended due date for ITR filing for AY 2025-26.\nFor assessees under Section 139(1) clause (a) (audit cases): Extended from 31 October 2025 to 10 December 2025.\nAudit report deadline: Extended to 10 November 2025.\nApplies to: Businesses/professionals requiring tax audit under 44AB, companies, firms.\nDoes NOT apply to: Salaried individuals, non-audit cases (their deadline was 31 July 2025).","last_updated":"2025-10-11","source":"CBDT Circular 15/2025"},
    {"id":"tax_year_concept","section":"IT Act 2025","category":"legislation","applies_to":["all"],"title":"Tax Year Concept (From April 2026)","content":"The Income Tax Act 2025 introduces the concept of TAX YEAR replacing the dual Previous Year / Assessment Year system.\nCurrently: Income earned in Previous Year 2025-26 is assessed in Assessment Year 2026-27.\nFrom April 2026: Simply 'Tax Year 2026-27' (the year in which income is earned AND assessed).\nIMPACT: Simplifies terminology. No change to actual tax computation or rates.\nAll references in forms, notices, and returns will use 'Tax Year' instead of 'PY' and 'AY'.","last_updated":"2026-03-20","source":"Income Tax Act 2025"},
    {"id":"ev_perquisite","section":"17(2)","category":"exemptions","applies_to":["salaried"],"title":"Electric Vehicle Perquisite Valuation (2026)","content":"IT Rules 2026 clarify the valuation of perquisite for employer-provided electric vehicles.\nIf employer provides EV for personal use: Perquisite calculated differently from ICE vehicles.\nCharging infrastructure provided by employer: May be exempt or valued at concessional rate.\nSpecific rules notified under IT Rules 2026 for EV-related benefits.\nThis is a new clarification under the rules effective April 2026.","last_updated":"2026-03-20","source":"IT Rules 2026, CBDT Notification 22/2026"},
    {"id":"refund_delays","section":"143(1)","category":"compliance","applies_to":["all"],"title":"Income Tax Refund Processing — Current Status","content":"As of FY 2024-25: IT Department issued ₹3.92 lakh crore in refunds (up to Feb 2025).\nHigher refund claims (>₹50,000 or higher than previous year) face delays due to verification.\nDepartment uses expanded database (AIS, TIS, Form 26AS) to verify each claim.\nCOMMON DELAY REASONS: Mismatch between ITR and Form 26AS/AIS, incorrect bank details, un-verified ITR, outstanding tax demand.\nACTION: E-verify ITR within 30 days. Pre-validate bank account. Check for mismatches in AIS before filing.\n27 lakh refund cases pending as per Finance Committee report (March 2026).","last_updated":"2026-03-01","source":"CBDT data, Finance Committee report"},
    {"id":"significant_transactions","section":"285BA","category":"compliance","applies_to":["all"],"title":"Significant Transactions — AIS/TIS Monitoring","content":"The IT Department sends emails about 'significant transactions' detected in Annual Information Statement (AIS).\nTransactions monitored: High-value purchases (property >₹30L, vehicles, jewelry >₹5L), cash deposits >₹10L, credit card payments >₹10L, mutual fund purchases >₹10L, foreign remittances, share transactions.\nIf you receive such an email: Verify your AIS on the e-filing portal. If transaction is correct, ensure it's reported in ITR. If incorrect, file feedback on AIS.\nThis is part of CBDT's advance tax e-campaign for AY 2026-27.\nNOT a notice — it's informational. But ignoring it may trigger scrutiny.","last_updated":"2026-03-15","source":"IT Department e-campaign"},

]


def search_knowledge(query, taxpayer_type="all", category=None):
    results = []
    ql = query.lower()
    for e in TAX_KNOWLEDGE_BASE:
        if taxpayer_type != "all" and taxpayer_type not in e["applies_to"] and "all" not in e["applies_to"]:
            continue
        if category and e["category"] != category:
            continue
        if ql in e["title"].lower() or ql in e["content"].lower():
            results.append(e)
    return results

def get_by_section(section):
    for e in TAX_KNOWLEDGE_BASE:
        if section.lower() in e["section"].lower():
            return e
    return None

def get_all_deductions():
    return [e for e in TAX_KNOWLEDGE_BASE if e["category"] == "deductions"]

def get_for_taxpayer_type(taxpayer_type):
    return [e for e in TAX_KNOWLEDGE_BASE if taxpayer_type in e["applies_to"] or "all" in e["applies_to"]]

def get_all_categories():
    return list(set(e["category"] for e in TAX_KNOWLEDGE_BASE))

def format_for_llm_context(entries, max_entries=5):
    parts = []
    for e in entries[:max_entries]:
        parts.append(f"## {e['title']} (Section {e['section']})\n{e['content']}\n[Source: {e['source']}] [Updated: {e['last_updated']}]")
    return "\n\n---\n\n".join(parts)
